### ISSUE TITLE
Busca de dados na linha de comando não está funcionando

### ISSUE THREAD

**Issue by kemelzaidan** [aparabolica/mananciais#2]
O exemplo apresentado no README não está funcionando:

``` javascript
$ node mananciais.js -d 2013-1-2

/Users/kemelzaidan/src/mananciais/server/app.js:25
        csv().from.path('data/data.csv', {
        ^
TypeError: object is not a function
    at Object.<anonymous> (/Users/kemelzaidan/src/mananciais/server/app.js:25:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kemelzaidan/src/mananciais/mananciais.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Alguma mudança de API, talvez?

**Comment by miguelpeixe** [comment]
Resolvemos desabilitar o CLI, não estava servindo de muita coisa e com as alterações no html da SABESP acabou trazendo mais problemas.
